name: Manage Repository Labels

on:
  label:
    types:
      - created
      - edited
      - deleted
  schedule:
    - cron: "45 4 * * *"

jobs:
  sync_labels:
    name: Sync repo labels with declarative label definition
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
